from datetime import datetime


def get_seed_payload() -> dict:
    return {
        "customers": [
            {
                "customer_id": "CUST1001",
                "full_name": "Aisha Rahman",
                "email": "aisha.rahman@example.com",
                "phone": "+966500100101",
                "segment": "Premier",
                "risk_tier": "Low",
                "relationship_since": "2018-04-11",
                "preferred_branch": "Riyadh Digital Branch",
                "country": "Saudi Arabia",
            },
            {
                "customer_id": "CUST1002",
                "full_name": "Omar Nasser",
                "email": "omar.nasser@example.com",
                "phone": "+966500200202",
                "segment": "Mass Affluent",
                "risk_tier": "Medium",
                "relationship_since": "2020-08-17",
                "preferred_branch": "Jeddah Corniche Branch",
                "country": "Saudi Arabia",
            },
        ],
        "accounts": [
            {
                "account_id": "ACC1001",
                "customer_id": "CUST1001",
                "account_type": "Checking",
                "account_name": "Primary Salary Account",
                "account_number_masked": "****3210",
                "currency": "SAR",
                "available_balance": 45872.35,
                "ledger_balance": 45925.35,
                "status": "Active",
                "iban_masked": "SA44****3210",
                "branch_name": "Riyadh Digital Branch",
                "opened_at": "2018-04-11",
            },
            {
                "account_id": "ACC1002",
                "customer_id": "CUST1001",
                "account_type": "Savings",
                "account_name": "Travel Goals Savings",
                "account_number_masked": "****7788",
                "currency": "SAR",
                "available_balance": 128400.00,
                "ledger_balance": 128400.00,
                "status": "Active",
                "iban_masked": "SA55****7788",
                "branch_name": "Riyadh Digital Branch",
                "opened_at": "2019-06-22",
            },
            {
                "account_id": "ACC2001",
                "customer_id": "CUST1002",
                "account_type": "Checking",
                "account_name": "Household Account",
                "account_number_masked": "****9931",
                "currency": "SAR",
                "available_balance": 17350.40,
                "ledger_balance": 17350.40,
                "status": "Active",
                "iban_masked": "SA61****9931",
                "branch_name": "Jeddah Corniche Branch",
                "opened_at": "2020-08-17",
            },
        ],
        "cards": [
            {
                "card_id": "CARD1001",
                "customer_id": "CUST1001",
                "account_id": "ACC1001",
                "card_type": "Credit",
                "network": "Visa Signature",
                "masked_number": "**** 5544",
                "status": "Active",
                "available_credit": 22850.10,
                "credit_limit": 35000.00,
                "reward_points": 126430,
                "payment_due_date": "2026-03-28",
                "expires_on": "2028-09-30",
            },
            {
                "card_id": "CARD1002",
                "customer_id": "CUST1001",
                "account_id": "ACC1001",
                "card_type": "Debit",
                "network": "Mada",
                "masked_number": "**** 1022",
                "status": "Active",
                "available_credit": None,
                "credit_limit": None,
                "reward_points": 0,
                "payment_due_date": None,
                "expires_on": "2027-12-31",
            },
            {
                "card_id": "CARD2001",
                "customer_id": "CUST1002",
                "account_id": "ACC2001",
                "card_type": "Credit",
                "network": "Mastercard Platinum",
                "masked_number": "**** 8821",
                "status": "Active",
                "available_credit": 9100.00,
                "credit_limit": 15000.00,
                "reward_points": 35210,
                "payment_due_date": "2026-03-25",
                "expires_on": "2027-11-30",
            },
        ],
        "transactions": [
            {
                "transaction_id": "TXN1001",
                "account_id": "ACC1001",
                "transaction_type": "Debit",
                "amount": 245.90,
                "currency": "SAR",
                "transfer_type": "Bill Payment",
                "category": "Utilities",
                "description": "Electricity Company bill payment",
                "transaction_date": "2026-03-15T08:15:00+00:00",
            },
            {
                "transaction_id": "TXN1002",
                "account_id": "ACC1001",
                "transaction_type": "Debit",
                "amount": 520.00,
                "currency": "SAR",
                "transfer_type": "Bill Payment",
                "category": "Utilities",
                "description": "STC bill payment",
                "transaction_date": "2026-03-13T11:25:00+00:00",
            },
            {
                "transaction_id": "TXN1003",
                "account_id": "ACC1001",
                "transaction_type": "Credit",
                "amount": 18500.00,
                "currency": "SAR",
                "transfer_type": "Salary Credit",
                "category": "Salary",
                "description": "March salary credit",
                "transaction_date": "2026-03-01T05:30:00+00:00",
            },
            {
                "transaction_id": "TXN1004",
                "account_id": "ACC1002",
                "transaction_type": "Credit",
                "amount": 5000.00,
                "currency": "SAR",
                "transfer_type": "Savings Credit",
                "category": "Savings",
                "description": "Savings top-up",
                "transaction_date": "2026-03-02T10:00:00+00:00",
            },
            {
                "transaction_id": "TXN2001",
                "account_id": "ACC2001",
                "transaction_type": "Debit",
                "amount": 890.00,
                "currency": "SAR",
                "transfer_type": "Internal Transfer",
                "category": "Transfer",
                "description": "Transfer to School Fees",
                "transaction_date": "2026-03-14T14:40:00+00:00",
            },
            {
                "transaction_id": "TXN1005",
                "account_id": "ACC1001",
                "transaction_type": "Debit",
                "amount": 4200.00,
                "currency": "SAR",
                "transfer_type": "Internal Transfer",
                "category": "Transfer",
                "description": "Transfer to Landlord",
                "transaction_date": "2026-03-01T08:00:00+00:00",
            },
            {
                "transaction_id": "TXN1006",
                "account_id": "ACC1001",
                "transaction_type": "Debit",
                "amount": 750.00,
                "currency": "SAR",
                "transfer_type": "Internal Transfer",
                "category": "Transfer",
                "description": "Transfer to Mum",
                "transaction_date": "2026-02-25T17:15:00+00:00",
            },
            {
                "transaction_id": "TXN1007",
                "account_id": "ACC1002",
                "transaction_type": "Debit",
                "amount": 520.00,
                "currency": "SAR",
                "transfer_type": "Bill Payment",
                "category": "Utilities",
                "description": "SEC Utilities bill payment",
                "transaction_date": "2026-03-10T09:30:00+00:00",
            },
            {
                "transaction_id": "TXN1008",
                "account_id": "ACC1001",
                "transaction_type": "Debit",
                "amount": 1200.00,
                "currency": "SAR",
                "transfer_type": "Internal Transfer",
                "category": "Transfer",
                "description": "Transfer to Brother",
                "transaction_date": "2026-03-05T20:05:00+00:00",
            },
            {
                "transaction_id": "TXN2002",
                "account_id": "ACC2001",
                "transaction_type": "Debit",
                "amount": 4600.00,
                "currency": "SAR",
                "transfer_type": "Internal Transfer",
                "category": "Transfer",
                "description": "Transfer to Apartment Rent",
                "transaction_date": "2026-03-03T06:50:00+00:00",
            },
        ],
        "payees": [
            {
                "payee_id": "PAYEE1001",
                "customer_id": "CUST1001",
                "nickname": "Landlord",
                "bank_name": "Riyadh Bank",
                "account_number_masked": "****9081",
                "category": "Rent",
                "status": "Verified",
                "last_used_at": "2026-03-01T08:00:00+00:00",
            },
            {
                "payee_id": "PAYEE1002",
                "customer_id": "CUST1001",
                "nickname": "Mum",
                "bank_name": "Al Rajhi",
                "account_number_masked": "****1122",
                "category": "Family",
                "status": "Verified",
                "last_used_at": "2026-02-25T17:15:00+00:00",
            },
            {
                "payee_id": "PAYEE1003",
                "customer_id": "CUST1001",
                "nickname": "SEC Utilities",
                "bank_name": "Saudi National Bank",
                "account_number_masked": "****4433",
                "category": "Utilities",
                "status": "Verified",
                "last_used_at": "2026-03-10T09:30:00+00:00",
            },
            {
                "payee_id": "PAYEE1004",
                "customer_id": "CUST1001",
                "nickname": "Brother",
                "bank_name": "Bank Albilad",
                "account_number_masked": "****7781",
                "category": "Family",
                "status": "Verified",
                "last_used_at": "2026-03-05T20:05:00+00:00",
            },
            {
                "payee_id": "PAYEE2001",
                "customer_id": "CUST1002",
                "nickname": "School Fees",
                "bank_name": "Saudi National Bank",
                "account_number_masked": "****6677",
                "category": "Education",
                "status": "Verified",
                "last_used_at": "2026-02-28T07:45:00+00:00",
            },
            {
                "payee_id": "PAYEE2002",
                "customer_id": "CUST1002",
                "nickname": "Apartment Rent",
                "bank_name": "Riyad Bank",
                "account_number_masked": "****2244",
                "category": "Rent",
                "status": "Verified",
                "last_used_at": "2026-03-03T06:50:00+00:00",
            },
        ],
        "transfers": [
            {
                "transfer_id": "TRF1001",
                "customer_id": "CUST1001",
                "from_account_id": "ACC1001",
                "payee_id": "PAYEE1001",
                "amount": 4200.00,
                "currency": "SAR",
                "transfer_type": "Internal Transfer",
                "category": "Transfer",
                "reference_note": "Transfer to Landlord",
                "created_at": "2026-03-01T07:55:00+00:00",
            },
            {
                "transfer_id": "TRF1002",
                "customer_id": "CUST1001",
                "from_account_id": "ACC1001",
                "payee_id": "PAYEE1002",
                "amount": 750.00,
                "currency": "SAR",
                "transfer_type": "Internal Transfer",
                "category": "Transfer",
                "reference_note": "Transfer to Mum",
                "created_at": "2026-02-25T17:10:00+00:00",
            },
            {
                "transfer_id": "TRF1003",
                "customer_id": "CUST1001",
                "from_account_id": "ACC1002",
                "payee_id": None,
                "amount": 520.00,
                "currency": "SAR",
                "transfer_type": "Bill Payment",
                "category": "Utilities",
                "reference_note": "SEC Utilities bill payment",
                "created_at": "2026-03-10T09:27:00+00:00",
            },
            {
                "transfer_id": "TRF1004",
                "customer_id": "CUST1001",
                "from_account_id": "ACC1001",
                "payee_id": "PAYEE1004",
                "amount": 1200.00,
                "currency": "SAR",
                "transfer_type": "Internal Transfer",
                "category": "Transfer",
                "reference_note": "Transfer to Brother",
                "created_at": "2026-03-05T20:03:00+00:00",
            },
            {
                "transfer_id": "TRF2001",
                "customer_id": "CUST1002",
                "from_account_id": "ACC2001",
                "payee_id": "PAYEE2002",
                "amount": 4600.00,
                "currency": "SAR",
                "transfer_type": "Internal Transfer",
                "category": "Transfer",
                "reference_note": "Transfer to Apartment Rent",
                "created_at": "2026-03-03T06:45:00+00:00",
            },
        ],
        "seeded_at": datetime.utcnow().isoformat(),
    }
